version: "3"
services:  
  node:
    image: "node"
    container_name: "node_env"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports: 
      - 3000:3000
    expose:
      - "3000"
    command: "npm start"
    

